site_name: 2022 February Common Fund Hackathon

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Information for Participants: participants.md
    - About the Data: about.md
    - Schedule: schedule.md
    - Code of Conduct: code.md
